### ISSUE TITLE
Support Date and Time types

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/prisma2#1059]
I know custom types are not supported yet, but I wonder why `Date` and `Time` are not currently supported as all of the currently supported DBs have support for those types either directly or through an integrated function (SQLite).

There are multiple use cases for those types and not having them makes working with date and time unclear - timezone is another issue by itself. Not being able to save `11:00`  or `2019-12-10` and then filter over it means that I need to do all sorting and filtering on the backend which makes the request inefficient on larger datasets.

**Comment by pantharshit00** [comment]
Right now we provide a `DateTime` which you can use to handle dates: https://github.com/prisma/prisma2/blob/0ee8b9146cb5159189963f1135715f745a28541b/docs/core/connectors/postgresql.md#data-model-mapping


For more customizable date types, you do have to wait for custom types.

**Comment by malekjaroslav** [comment]
I am using DateTime, but it js inconvenient for a lot os use cases. Is there some eta for custom types?

**Comment by pantharshit00** [comment]
I can't give you an ETA on native database types right now as it is ongoing in terms of product and implementation. There are still some unresolved concerns that we have right now.

**Comment by divyenduz** [comment]
Native database types are being tracked here https://github.com/prisma/prisma2/issues/446

Since the question of DateTime is answered in this thread, I am closing this one. 

Please feel free to comment and tag me if you disagree, happy to reopen this issue. 

If there is another specific type that you are about, please create a new feature request for it.
