### ISSUE TITLE
[Introspection] `information_schema` does not want to be introspected

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1073]
Windows, MySQL 5.7:

```
prisma2 introspect --url="mysql://root:root@localhost:3306/information_schema" --print > information_schema.log 2> information_schema_stderr.log
```

`information_schema_stderr.log` is only:

```
Error: Empty introspection result for mysql://root:root@localhost:3306/information_schema
```

while:

![image](https://user-images.githubusercontent.com/183673/70394070-81941600-19f1-11ea-82a0-33a84d65387e.png)

**Comment by janpio** [comment]
Permission problem? On some servers it seems to work.

**Comment by divyenduz** [comment]
@janpio: I think that @do4gr can answer this better. I know that introspection gets the data for all the other tables through `information_schema` and it shouldn't contain information about itself. 

It returning empty introspection is expected result for me because the queries that we use to introspect won't return a result set for it.

**Comment by divyenduz** [comment]
> Permission problem? On some servers it seems to work.

When it works, what schema does it return?
