### ISSUE TITLE
Netlify: Document why we need a specific configuration

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1086]
To make Prisma Client JS work with Netlify Functions, we need the following configuration: 

```
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
```

This is because the netlify runtime is similar to AWS lambda which powers it and rhel linux is expected. 

This might be a bit confusing to the users if they try to log the OS in the netlify's build step which is Ubuntu. But we don't need to make any configurational changes to make Prisma CLI (I think the only build step use case?) work as it is freshly installed on that platform. 

We may want to document this behavior. 

Related issue: https://github.com/prisma/photonjs/issues/324

(Note that you might need [additional steps](https://github.com/prisma/prisma-examples/blob/prisma2/deployment-platforms/netlify/build.sh) to ensure that this binary is bundled with netlify because netlify CI as of February 2020 uses an older version of ZISI which does not include this fix https://github.com/netlify/zip-it-and-ship-it/issues/77)

**Comment by 2color** [comment]
I'm trying to better understand the two approaches for documentation and examples purposes. 
I've looked at https://github.com/prisma/prisma2-e2e-tests/issues/46#issuecomment-590989874 and the e2e tests code.

From what I understand, there are two possible build-approaches with Netlify:
1. The default uses [zip-it-and-ship-it](https://github.com/netlify/zip-it-and-ship-it) when `netlify deploy` is called which packages the functions into a zip so that they can be deployed to Lambda by Netlify.
2. Using the new Netlify Build. Provides more customisation options for build lifecycle. Currently has beta status. 

Both approaches use the [Netlify Build Image](https://github.com/netlify/build-image) during build time which is different to the Lambda runtime. That's why we want to be able to run the build in the same image as the runtime (see https://github.com/netlify/build/issues/730) so we don't have to explicitly define the `binaryTargets` in the `schema.prisma` for the runtime. 

Approach 2 (Netlify Build) uses a different version of `netlify/zip-it-and-ship-it` by default, which solves [the missing binary](https://github.com/netlify/zip-it-and-ship-it/issues/77)

## Open questions

1. Do both approaches use `netlify/zip-it-and-ship-it` for packaging the functions and their dependencies? 

Answer: Yes [according to this comment](https://github.com/netlify/zip-it-and-ship-it/issues/81#issuecomment-578265296)

2. How does the build process differ (`netlify/zip-it-and-ship-it` version?) when running **locally** vs. on Netlify's build environment/CI with Github integration

## Current challenges

## Binary missing at runtime

- When deploying from the CLI (both approaches) 
- Works when deploying with Github integration (and ensuring the new version of `netlify/zip-it-and-ship-it` is used)

### Getting both approaches to work with *zero-config*, namely:
1. With both approaches, we still need to specify the `binaryTargets`.
2. With approach 1 we need to set the `ZISI_VERSION` env var to make sure the latest version of `netlify/zip-it-and-ship-it` is used which fixes the missing binary problem.

**Comment by 2color** [comment]
This is addressed in the new deployment guide.

It’s also encoded in the deployment example https://github.com/prisma/deployment-example-netlify/blob/master/netlify.toml
