### ISSUE TITLE
Photon Binary Engine downloading

### ISSUE THREAD

**Issue by shah05** [prisma/prisma2#1143]
Hi,

Just wondering, if let say I have multiple database that I want introspect and query data from. Is there a need to download multiple binary query engine as well for each DB via "Prisma2 Generate" ? Or I can just use the generated PhotonAPI script (Index.js) for each DB but it runs using the same binary query engine ?

**Comment by pantharshit00** [comment]
If you are using environment variables for datasources, you don't need to regenerate the client again as you can just specify the env variable.

If you are hard coding those values, you do need to regenerate the client in order to update the database credentials in the generated client. 

Also, we don't redownload the binary every time you generate, it gets fetched from the cache if the binary was already downloaded.
