### ISSUE TITLE
Error SqlState("42P01") - when running tests with new db schema

### ISSUE THREAD

**Issue by typedef42** [prisma/prisma2#1161]
Hi, 

As discussed in slack, I ran into an error when running e2e tests, using a random schema on the same DB as dev code is running. 
```js
Invalid `const maker = await this.photon.makers.create()` invocation

Reason: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P01"), message: "relation \"test.Maker\" does not exist", detail: None, hint: None, position: Some(Original(13)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(1173), routine: Some("parserOpenTable") }) }
```

When running tests I have a pre-test hook that runs `prisma2 lift up` on the DB connection with the random schema name, but I don't have prisma studio up (nor `prisma dev`) when running tests. Could it be a problem?

A reproducible repository is here: https://github.com/typedef42/prisma2-test-sqlstate-42p01

**Comment by pantharshit00** [comment]
Hi,

I checked your reproduction. Problem is that your test setup script is executing `prisma2 lift up` it there is no migrations that it can apply. The migrations that are created in dev mode are not applied by it. So you will need to run `prisma2 lift save` so that you can save the current state your datamodel as a migration. Then you can run `prisma2 lift up` to apply that migration. Right now what is happening, prisma2 is not creating any tables in your database and it is throwing that column not found error.

So after doing that and remove expect block from title(it is not in your test data), your tests are passing:
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/22195362/71022671-089a6a00-2127-11ea-9f56-83c8b2a17f9f.png">

**Comment by typedef42** [comment]
Thank you @pantharshit00, I knew I was missing something with lift, but could not figure out what.
I guess I'm going to call `prisma lift save` somewhere in my npm scripts, maybe on a release script or even add it in the pre-hook tests too!
