### ISSUE TITLE
Add an example with Prisma and Apollo Server in plain GraphQL without Nexus 

### ISSUE THREAD

**Issue by andreasanta** [prisma/prisma2#1281]
(stems from issue #929 )

The current [Apollo Server example for Prisma](https://github.com/prisma/prisma-examples/tree/prisma2/typescript/graphql-apollo-server) makes use of the Nexus library, which is very useful for specific use cases, but might not be required by a potential developer, and it even introduces an additional level of complexity to the learning curve.

Please add an example with Apollo Server that leverages only GraphQL schema and prisma.schema for schema definition, with no other middleware besides Photon and Lift.

I believe this would allow a faster onboarding for newcomers from Apollo!

Thanks!

**Comment by Mokhir** [comment]
Can we get an ETA on this? Really dislike nexus as a whole. I believe it deters a lot of first-time Prisma2 users from touching it, especially if they don't understand that nexus is removable.

**Comment by wqawasmi** [comment]
+1 on this. Would be really clarifying.

**Comment by ScottWallace** [comment]
Would love this as well, in the meantime, would appreciate a quick answer.  I'm presuming the `prisma generate` command creates everything needed for an ApolloServer config, but I'm missing the `schema: ` and `resolvers:` values.  If @andreasanta, @nikolasburk, or anyone else could post your config for ApolloServer and the correct values from the generated Photon, I'd appreciate it.  

Just looking for where within the generated Photon I can get .schema and/or .resolvers, and, yes, I have run `prisma2 generate`.

Here's my app.js, your mileage may vary:

```
import express from 'express';
import { ApolloServer } from 'apollo-server-express';

import bodyParser from 'body-parser';
import compression from 'compression';

import { Photon } from '@prisma/photon';


const photon = new Photon()
const app = express();

app.use(bodyParser.json());
app.use(compression());

const useIntrospection = !(process.env.NODE_ENV == 'production');
const usePlayground = !(process.env.NODE_ENV == 'production');

const server = new ApolloServer({
  context: photon,
  schema: photon.?????, // What the heck is this supposed to be?
  resolvers: photon.?????, /// Also this?
  introspection: useIntrospection, // enables introspection of the schema
  playground: usePlayground, // enables the actual playground
});

// Link the Express app and Apollo Server
server.applyMiddleware({ app });

if (process.env.NODE_ENV == 'production') {
  app.listen(8080);
}
else {
  app.listen(5555);
}
```
Please don't tell me I have to go through the whole Nexus setup of all of this stuff, that would not just be a pain, it would also defeat the purpose of generating things from the original schema.prisma.

Thanks!

**Comment by Mokhir** [comment]
@ScottWallace 

Hey, I am curious if you can expand your question a bit.

See according to the [ApolloServer doc](https://www.apollographql.com/docs/apollo-server/api/apollo-server/), the constructor can take in the arguments of 
1. typeDefs & resolvers
or 
2. schema    - (defined as `An executable GraphQL schema that will override the typeDefs and resolvers provided.`)

So when you are asking what to set `schema: x` and at the same time set `resolvers: x`, that seems a bit confusing because if you had a schema set in the constructor, it would override whatever value you set for the resolver argument.


Now if you want to generate your own schema, it's done through the [graphql-tools lib](https://www.apollographql.com/docs/apollo-server/api/graphql-tools/) that combines a typeDefs & resolvers & a bunch of other optional arguments and spits out a `schema` which you can pass as an arg to the ApolloServer constructor.

So please expand a bit what you are looking for here with the prisma generate? Are you expecting the prisma schema to code-gen a schema file for you so you don't have to write resolvers for your apollo server?

---

An alternative to using nexus for me was to remove all the nexus components and write the ApolloServer myself. 
I have a typeDefs for my graphql schema which is slightly different than my prisma schema (you don't want a 1:1 schema because you want to hide some database fields for example).
I have a resolvers section defined as well, and in each resolver I have business logic written that calls 
`return await photon.users.findOne({ where: { email: "bob@github.com"} }).include({posts:true})`
for example.

^That I believe is the real alternative to using nexus and writing the resolvers in the data objects.

**Comment by ScottWallace** [comment]
I'm looking for something like is described in the link below, which is geared to the original Prisma, not Prisma2. I think it's reasonable to ask whether, amongst the Photon generated stuff, there's enough information to properly populate the Apollo Server config, whatever that might be, typeDef, schema, etc. - it's a generator after all.  Following the example in the link, perhaps a photon.typeDefs, or photon.schema, or whatever, I don't care, I just want to populate the Apollo Server config in whatever manner Photon offers, if it does.

I use generators to save time.  Time is my enemy.  I've got things to do, and creating hundreds of boilerplate lines after I've run a generator is not my thing.  I get that Photon is an ORM generator, but to really support Apollo, and better support Yoga, this would be helpful, and I agree with OP, introducing Nexus isn't the right answer, unless it has to be.  

I'd like Prisma's answer, is `nexus-prisma` the choice, or is there something buried in the generated Photon that allows me to duplicate the original non-Prisma2 command `graphql get-schema`?  If not, perhaps there should be?

If someone's done this without Nexus, please post a quick code fragment, rather than our waiting on the requested official code example.  If no one has it, I'll wait for the official example.

[Directly passing Prisma generated schema to Apollo server. Downsides?](https://www.prisma.io/forum/t/directly-passing-prisma-generated-schema-to-apollo-server-downsides/6588)

(FYI, I'm not concerned about what I graphgl functions I expose, because I'll be adding authentication middleware.)

**Comment by harrysolovay** [comment]
I agree that this is a bit confusing... a Nexus-free template would go a long way!

**Comment by nikolasburk** [comment]
Hey everyone, thanks a lot for sharing your thoughts here! 🙌  I just added SDL-first examples that are based on plain usage of Apollo's `graphql-tools` instead of GraphQL Nexus, you can find them here:

- for [Node.js](https://github.com/prisma/prisma-examples/tree/prisma2/javascript/graphql-sdl-first)
- for [TypeScript](https://github.com/prisma/prisma-examples/tree/prisma2/typescript/graphql-sdl-first)

Hope that helps, let me know if you have any questions! 🙌

**Comment by nargetdev** [comment]
Updated link since Prisma2 was merged to master:
[Node.js](https://github.com/prisma/prisma-examples/tree/master/javascript/graphql-sdl-first)
[TypeScript](https://github.com/prisma/prisma-examples/tree/master/typescript/graphql-sdl-first)

**Comment by andreasanta** [comment]
Many thanks @nicolasburk and @nargetdev!

**Comment by Sevensidedmarble** [comment]
Sorry if this is a dumb question but I've read through the SDL-version, which is much appreciated since I don't know Nexus but I'm still confused. I thought Apollo Server could generate default resolvers, and I thought Prisma could generate type definitions. Is all the content of the Schema file really necessary in those examples?

**Comment by janpio** [comment]
Not a dumb question, but not the optimal place to ask: Better use https://github.com/prisma/prisma/discussions or open an issue in the [example repository](https://github.com/prisma/prisma-examples/issues).
