### ISSUE TITLE
prisma2 generate is trying to download from incorrect url (debiandebian-openssl-1.1.x/prisma.gz)

### ISSUE THREAD

**Issue by sergejgritsenya** [prisma/prisma2#1301]
ENV:
docker: FROM node:13-slim
prisma2: 2.0.0-preview019

Execution of command ```RUN NODE_ENV=development prisma2 generate``` in docker results in error: ```Error: Not Found https://prisma-builds.s3-eu-west-1.amazonaws.com/master/e7579bd35e0938dbf773f1706c098a0d14a5a038/debiandebian-openssl-1.1.x/prisma.gz
at p_retry_1.default.retries (/usr/local/share/.config/yarn/global/node_modules/prisma2/build/index.js:35668:23)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async RetryOperation._fn (/usr/local/share/.config/yarn/global/node_modules/prisma2/build/index.js:29946:12) {
attemptNumber: 1,
retriesLeft: 1
}```

If I get it right, the link is generated wrong since it does not work. Note that it contains debiandebian instead of debian.

The link should be(working link):  https://prisma-builds.s3-eu-west-1.amazonaws.com/master/e7579bd35e0938dbf773f1706c098a0d14a5a038/debian-openssl-1.1.x/prisma.gz

Execute pure docker build (docker system prune -a)

It worked fine 04 Jan 2020

**Comment by hitochan777** [comment]
@sergejgritsenya
This might be because of recent update of node docker image. 
node:13-slim is updated and now it references node:13.6.0-slim. 
I had the same problem in node:12-slim. For a temporary fix, I fixed the image version to the previous version which is `node:12.14.0-slim`, and it works.

In order for `prisma2 generate` to work with the latest node image, I believe [this part of code on photonjs](https://github.com/prisma/photonjs/blob/master/packages/get-platform/src/getPlatform.ts#L154) needs to be fixed.
I think `'debian-openssl-1.1.x'` should be `'-openssl-1.1.x'` as `distro` takes care of the `debian` part.
```javascript
  if (distro) {
    return (distro + 'debian-openssl-1.1.x') as Platform
  }
```

**Comment by pantharshit00** [comment]
I can confirm this, dockerfile for reproduction:
```Dockerfile
FROM node:13-slim
RUN uname -a

ADD ./ /opt/app
WORKDIR /opt/app

RUN rm -rf node_modules \
  && npm i -g prisma2@latest  \
  && npm install

RUN prisma2 generate

CMD ["npm", "run", "dev"]
```

**Comment by steebchen** [comment]
Thanks for the bug report! @timsuchanek already fixed this via https://github.com/prisma/photonjs/commit/ab201b4307203991d53f1709fa45b725974afded.
You can try this fix by temporarily upgrading to `prisma2@alpha`.

If you get an error similar to `error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`, you need to install OpenSSL in your docker file. I recommend to do that at the very top:

```
FROM node:13-slim

RUN apt-get -qy update
RUN apt-get -qy install openssl

# ...
```

**Comment by timsuchanek** [comment]
Correct! And we just added an error message to help to get out of this situation:
```
Your linux installation misses the openssl package. You can install it like so:
apt-get -qy update && apt-get -qy install openssl
```
