### ISSUE TITLE
Empty introspection result for mysql

### ISSUE THREAD

**Issue by hatchli** [prisma/prisma2#1457]
I have a mysql database setup on aws (RDS). It's brand new with nothing in it.
When I do `npx prisma2 introspect` I get:
`(node:7344) ExperimentalWarning: The fs.promises API is experimental
Introspecting based on datasource defined in prisma\schema.prisma …
Error: Empty introspection result for mysql://{myusername}:{mypassword}@{id}.us-east-2.rds.amazonaws.com:3306/prisma
PS C:\Users\{me}\Documents\GitHub\Prisma2\Backend> `

My schema.prisma:
```
datasource db {
  provider = "mysql"
  // other options are: "mysql" and "sqlite"
  url      = "mysql://{myusername}:{mypassword}@{id}.us-east-2.rds.amazonaws.com:3306/prisma"
}
generator client {
  provider = "prisma-client-js"
}
```

I'm honestly just trying to learn Prisma 2 for my next project. I would like the stack to be serverless with Now / Next.js / React / and Prisma 2. Maybe I'm being an idiot... I'm new to backend stuff, but did manage to get a website going on Prisma 1.34 before. Any help would be appreciated!
`

**Comment by janpio** [comment]
If your database is empty, this is pretty much what is expected - you can not introspect any Prisma schema from an empty database.

What are you trying to do?
If you want to test out Prisma with an example project, you might want to look at: https://github.com/prisma/prisma-examples

**Comment by nikolasburk** [comment]
Hey @hatchli, thanks a lot for opening this issue 🙏as @janpio mentioned, `prisma2 introspect` indeed expects a database that already has a schema, that's why it failed for you. 

There are two major ways how you can use Prisma:

- Option A: Perform SQL migrations manually, introspect your DB schema to generate Prisma's data model and finally generate Prisma Client to be able to work programmatically with your database
- Option B: Use Prisma Migrate to perform migrations by mapping your (manually written) Prisma schema to the DB. Then generate Prisma Client to be able to work programmatically with your database.

Note that Prisma Migrate (option B) is currently in an **experimental state** and we officially recommend to go with option A until Prisma Migrate is in a production-ready state. 

Definitely check out these resources to get started with Prisma:

- [Getting Started](https://github.com/prisma/prisma2/blob/master/docs/getting-started.md)
- [Prisma Examples](https://github.com/prisma/prisma-examples/) 

Please let me know if that helps of if you have any further questions, always happy to help! 🙂

**Comment by hatchli** [comment]
Thank you @janpio  and @nikolasburk ! I suppose I'm confused. What I am trying to do is start up a server without preexisting schema, because I want to start a new project from scratch. With Prisma 1.34, I simply wrote the schema and data model and resolvers, deployed, and then was good to go. I'm not "migrating" anything really. I've gone through the Getting Started, which presumed there's an existing database with a schema, and the Prisma Examples, which are helpful but don't enlighten me on how I would start a project from scratch using Prisma 2. I know I am missing something here, I'm just not sure what precisely.

**Comment by pantharshit00** [comment]
> I'm not "migrating" anything really. 

Prisma 1 actually automatically run the migration when you `prisma deploy`, there was no way to manage the migrations in that. Prisma 2 does that via migrate with additonal features.
