### ISSUE TITLE
[Introspection] No ID: Why does it sometimes error and sometimes panic?

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1515]
Investigate what is going on with ID errors and panics:

https://github.com/prisma/prisma2/issues/1113
https://github.com/prisma/prisma2/issues/1083

Why does it sometimes error and sometimes panic?
How is this even possible that the validator sometimes does not catch anything but lets it go to panic?

**Comment by janpio** [comment]
As the issues are some time old, we should probably start be reconfirming that the error messages actually still exist this way, and that what was identified back then as the problem of it is still true.

(https://github.com/prisma/prisma2/issues/1113 for example is internally described as "Panic: Model (probably) has @@id, but Query Engine panics because unsupported" which is very different from how the issue looks like when you click it an read the examples we/I chose in the past)

**Comment by do4gr** [comment]
This should now be fixed by #453
The problem was, that there was some hardcoded exception in the datamodel validator that was supposed to work together with TS introspection to allow Prisma M2M relation models to pass. It basically let through models without ids if they had two required relation fields.

That was not targeted enough and is also not needed anymore since the Rust introspection does not render models for Prisma M2M relations. 

Removing it turns the panics into validation errors as wanted.
