### ISSUE TITLE
Proposal: Move `prisma2` CLI into `@prisma/cli` npm package 

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#1548]
We're considering moving the `prisma2` CLI from the `prisma2` npm package into `@prisma/cli` similar to how [ionic](https://ionicframework.com/blog/a-new-package-for-the-cli/), [Angular](https://cli.angular.io/) and [vue](https://cli.vuejs.org/) are doing it.

Note that you'll still invoke the CLI via the `prisma2` command. For a global installation, this would be the upgrade flow:

```
$ npm uninstall -g prisma2
$ npm install -g @prisma/cli

# Invoke the new CLI from the new package:
$ prisma2 --help
```

Note that [we're planning to change the `prisma2` command to `prisma`](https://github.com/prisma/prisma2/issues/1549) upon the upcoming Prisma 2.0 launch.

## Pros

• Clearer package naming ("you know what you get")
• Easier to distinguish versions of individual packages
• More consistent: Unifying Prisma's tools under the `@prisma` npm [scope](https://docs.npmjs.com/about-scopes)

## Cons

• Another breaking change
• Easier to find/remember/understand when CLI package name and command are identical (e.g. `netlify-cli` npm package and `netlify` CLI command is one additional thing to remember)

**Comment by homoky** [comment]
I know that everything is in development phase right now, but I would really consider to think the most about those things in the beginning. For the newcomers and the community itself is not best to change regularly names of those things. Take example of Photon and Lift, it was strongly communicated and now it is renamed. For my viewpoint it makes harder to wrap your head around prisma2 to keep updated to those late updates.

**Comment by pantharshit00** [comment]
As mentioned in our internal discussion, moving `@prisma/cli` would break dx for `npx` as you would need to specify the package name if you don't have `@prisma/cli` locally installing:

```
npx -p @prisma/cli prisma2 .....
```

I think we should not move @prisma/cli unless we want to force global or local installation

**Comment by luhagel** [comment]
Kinda torn on this one, I think the most important thing is getting to a decision now, and then sticking with it.

Imho having all packages under @prisma/xyz feels a little cleaner, especially with the plans to rename the command anyways, so there will be differences no matter what.

Can't say I'm a big fan of another breaking change, ut I knew what I was gettng myself into.
---
On the `npx` side, I'm not to sure people using prisma with npx is even something to strife for, since it makes versioning extremely unreliablle and adds some quite significant overhead every time a command is run. Might be fine for runnning an`introspect`, but as soon as `generate` and `migrate` are a part of your workflow, npx shouldn't be a valid option anymore.

**Comment by janpio** [comment]
> On the `npx` side, I'm not to sure people using prisma with npx is even something to strife for, since it makes versioning extremely unreliablle and adds some quite significant overhead every time a command is run. Might be fine for runnning an`introspect`, but as soon as `generate` and `migrate` are a part of your workflow, npx shouldn't be a valid option anymore.

Common misconception about `npx`, unfortunately. If you have the package in your `package.json` and installed locally, it will just use the local package with almost no overhead. Then it is basically an alternative for npm scripts, without the need to edit your `package.json`.

**Comment by nikolasburk** [comment]
Since `npx` has been brought up a few times, I want to add a bit more context around this. 

**The general recommendation for installation of the Prisma 2 CLI is (and will be) to install it _locally_ as a dev dependency to avoid version conflicts**. 

When installed locally as a dev dependency, you can invoke the CLI by prefixing it with `npx` or `yarn`, see the [CLI installation docs](https://github.com/prisma/prisma2/blob/master/docs/prisma2-cli.md). This is / will be the recommended workflow for using the Prisma CLI going forward:

```
# npm
npm install prisma2 --save-dev
npx prisma2 # invokes the CLI

# yarn
yarn add prisma2 --dev
yarn prisma2 # invokes the CLI
```

So, another question of changing the npm package is what happens to the local installation and invocation flows. I've tested these scenarios with the `@vue/cli` package, here's the results. 

The following just works:

```
npm install @vue/cli --save-dev
npx vue --help # invokes the CLI
```

and

```
yarn add @vue/cli --dev
yarn vue --help  # invokes the CLI
```

If you don't have the CLI installed (neither globally nor locally), you can invoke it via `npx` like so:

```
npx @vue/cli --help  # invokes the CLI
```

The following doesn't work though:

```
npx vue --help # doesn't work, the npm package name is missing
```

**Comment by janpio** [comment]
As we also own `prisma`, we could in theory make `npx prisma` (the last case, that does not work for `npx vue`) work and tell the use to use the correct command once (and uninstall the `prisma` package again (or even to it semi automatically in the postinstall). But that would still be confusing, because after adding the local `@prisma/cli` dependency, the same command that just told them to do someething would then be the valid command to use the CLI.

**Comment by janpio** [comment]
This is live for `alpha` with `2.0.0-alpha.973` and will also happen with the next preview release 🚀
