### ISSUE TITLE
[Introspection] Relation guardrail creates duplicate fields

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1693]
```
Error: Schema parsing
error: Field "business_id" is already defined on model "Checkins".
  -->  schema.prisma:86
   | 
85 |   /// This used to be part of a relation to Business
86 |   business_id   Int     @default(0)
   | 
error: Field "day_id" is already defined on model "Checkins".
  -->  schema.prisma:90
   | 
89 |   /// This used to be part of a relation to Days
90 |   day_id        Int     @default(0)
   | 

Validation Error Count: 2
```

via model:

```
model Checkins {
  label_time_0  String?
  label_time_1  String?
  label_time_10 String?
  label_time_11 String?
  label_time_12 String?
  label_time_13 String?
  label_time_14 String?
  label_time_15 String?
  label_time_16 String?
  label_time_17 String?
  label_time_18 String?
  label_time_19 String?
  label_time_2  String?
  label_time_20 String?
  label_time_21 String?
  label_time_22 String?
  label_time_23 String?
  label_time_3  String?
  label_time_4  String?
  label_time_5  String?
  label_time_6  String?
  label_time_7  String?
  label_time_8  String?
  label_time_9  String?
  /// This used to be part of a relation to Business
  business_id   Int     @default(0)
  /// This used to be part of a relation to Business
  business_id   Int     @default(0)
  /// This used to be part of a relation to Days
  day_id        Int     @default(0)
  /// This used to be part of a relation to Days
  day_id        Int     @default(0)

  @@id([business_id, day_id])
  @@index([day_id], name: "day_id")
}
```

Something about `/// This used to be part of a relation to ...` seems to go wrong.

**Comment by janpio** [comment]
More occurrences:

https://github.com/prisma/introspection-engine-output/blob/a6f34a96c22713e6522a2767c8968c2ad251d2db/postgresql_private/email-carlos-rueda-mxm_stderr.log#L2-L37
https://github.com/prisma/introspection-engine-output/blob/a6f34a96c22713e6522a2767c8968c2ad251d2db/postgresql_private/email-carlos-rueda-mxm.log#L9-L20

(Might be the edge case you told me about @do4gr)

**Comment by divyenduz** [comment]
Ran into a similar error [here](https://github.com/prisma/introspection-engine-output/blob/test_utils/clients/results/postgresql_public_test_utils_opendota_generate_stderr.log), however, I am not sure if they are related to this issue. 

"What is a relation guardrail?" this context is missing for me to link them cc @janpio 

Assuming that they are the same issue unless proved otherwise. 

---

Internal notes: 

Test utils database(s) affected: 
- https://github.com/prisma/introspection-engine-output/blob/test_utils/clients/results/postgresql_public_test_utils_opendota_generate_stderr.log

**Comment by janpio** [comment]
This guardrail has been removed in https://github.com/prisma/prisma-engines/pull/578 - the error is gone 🚀
