### ISSUE TITLE
Cannot programmatically choose a datasource provider

### ISSUE THREAD

**Issue by Errorname** [prisma/prisma2#1760]
This is an issue that I have for [prisma-multi-tenant](https://github.com/Errorname/prisma-multi-tenant).

I am giving the possibility to the user to have whatever provider he wants for the "management" datasource. Before preview023 I did the following:

```prisma
datasource management_sqlite {
  provider = "sqlite"
  url      = env("PMT_MANAGEMENT_URL")
  enabled  = env("PMT_MANAGEMENT_PROVIDER_SQLITE")
}

datasource management_mysql {
  provider = "mysql"
  url      = env("PMT_MANAGEMENT_URL")
  enabled  = env("PMT_MANAGEMENT_PROVIDER_MYSQL")
}

datasource management_postgresql {
  provider = "postgresql"
  url      = env("PMT_MANAGEMENT_URL")
  enabled  = env("PMT_MANAGEMENT_PROVIDER_POSTGRESQL")
}
```

Based on what provider the user wanted, I was able to either enable or disable a datasource.

As we know, preview023 removed the enabled field: https://github.com/prisma/prisma2/issues/1512.

Note: If I keep the same schema, and run a migrate command it will now output `Error: Cannot read property 'enabled' of undefined` because it still looks for the field [here](https://github.com/prisma/migrate/blob/master/src/utils/ensureDatabaseExists.tsx#L24) to choose a datasource. **So we cannot have two datasources in the same schema.**

Since the `enabled` method isn't available, we need something else. However, the feature to have a dynamic provider isn't available yet: #1487. 

I'd suggest to re-add the `enabled` method until #1487 is implemented, or have another method to select a datasource (maybe check if URL is empty?).

**Comment by BjoernRave** [comment]
A "quick-fix" for this would be to allow setting the `provider` via an environement variable

**Comment by schickling** [comment]
Thanks for bringing this up @Errorname and your suggestion @BjoernRave. Due to the implementation complexity allowing env vars in the `provider` field is unfortunately not a feasible "quick-fix".

Enabling this workflow is definitely on our radar and a high priority – especially as also other frameworks (such as Redwood) rely on it. I can't promise any timeline yet but we'll be working towards it. I appreciate your patience in the meanwhile! 🙏 

I'm closing this issue in favor of https://github.com/prisma/prisma2/issues/1487 which will be the solution for this use case.
