### ISSUE TITLE
Prisma2 CLI prisma2@2.0.0-preview-2 generate the file not in the right place

### ISSUE THREAD

**Issue by tanghw** [prisma/prisma2#188]
Prisma2 CLI prisma2@2.0.0-preview-2 generate the file not in the right place,it locates in directory prisma

**Comment by pantharshit00** [comment]
This is expected. We have a convention to automatically pick up files inside the `prisma` folder. Your migrations will also get stored there.

**Comment by tanghw** [comment]
not this,I mean node_module/@generated in the prisma folder

**Comment by tanghw** [comment]
I tried,it's ok in prisma2@2.0.0-preview-1

**Comment by tanghw** [comment]
generator photon {
  provider = "photonjs"
}

generator nexus_prisma {
  provider = "nexus-prisma"
  output   = "node_modules/@generated/nexus-prisma"
}
node_modules/@generated/nexus-prisma is in prisma folder when it generated

**Comment by tvvignesh** [comment]
@pantharshit00 This creates an issue while running the typescript file as given here: https://github.com/prisma/prisma2/blob/master/docs/tutorial.md#76-use-photon-for-basic-reads-and-writes

I had generated the photonjs script using `prisma2 generate` and a node_modules folder was created within the prisma directory.

I tried running `npm start` and nothing happened, checked the DB - no records got inserted, Also, autocomplete did not work in VSCode. 

But when I changed the import statement to `import Photon from './prisma/node_modules/@generated/photon'` (specified the prisma folder as well), then everything started working - insertion happened to the database and also the autocomplete worked properly.

I feel that this is a bug to be addressed.

**Comment by timsuchanek** [comment]
Thanks for reporting @tvvignesh! So the path that you provide in the `output` field of the generator config will be resolved relative to the prisma dir.
Because of that, we advise to just keep the `output` field empty and let prisma resolve it, as we correctly find the current working directory to generate the node_modules.

**Comment by tvvignesh** [comment]
@timsuchanek Thanks for your quick reply. I had left the output field empty and it generated the files in the right place (inside prisma directory). But the problem is not that. The problem is only in importing the generated files from the directory in the ts file for which we have to specify the path relative to prisma directory as opposed to what is mentioned in the tutorial here: https://github.com/prisma/prisma2/blob/master/docs/tutorial.md#76-use-photon-for-basic-reads-and-writes

I guess the tutorial might need to be updated then to have Photon import from the node_modules within prisma folder rather than directly.
