### ISSUE TITLE
Zeit Now Deployment

### ISSUE THREAD

**Issue by james-ff** [prisma/prisma2#357]
Hey,

Has anyone got deployment to zeit's now platform working?

I'm using photon with graphql-nexus (@prisma/nexus), via ApolloServer in my use case

Cheers,

James

**Comment by williamluke4** [comment]
@james-ff  Check out https://github.com/fluidstackdev/fluidstack

**Comment by divyenduz** [comment]
@james-ff : Thanks for raising this, we have an example for that https://github.com/prisma/prisma-examples/tree/prisma2/deployment-platforms/zeit-now

**Comment by james-ff** [comment]
@divyenduz Hey, the example is good, but for my use case I'm looking for a template that includes graphql-nexus, I found this example, but having issues myself so far [https://nexus.js.org/docs/database-access-with-prisma-v2]

**Comment by iherger** [comment]
@james-ff , I made a small proof of concept (based on the official graphql-yoga/nexus example), which may be helpful: https://github.com/iherger/prisma2-now

**Comment by CaptainChemist** [comment]
Hey @james-ff I have a version that works with nexus, graphql-yoga, and next.js here: https://www.codemochi.com/blog/2019-08-12-prisma-2-now/

Have fun- I think this stack is great!

**Comment by ryanking1809** [comment]
Here's my working version based off the prisma2 boilerplate https://github.com/ryanking1809/prisma2-zeit-now

The main difference is I've put `prisma2 lift up` in the `package.json` `postinstall` script. It makes the migrations work but I'm not 100% sure it's the best place for it?
```
"scripts": {
    "start": "node src/index.js",
    "seed": "node prisma/seed.js",
    "postinstall": "prisma2 generate && prisma2 lift up"
  }
```

**Comment by iherger** [comment]
@ryanking1809 , my thoughts on putting `prisma2 lift up` in postinstall: a) shouldn't you do `prisma2 lift up` before `prisma2 generate`, so that you are generating the correct photon binary? and b) like this, you will automatically migrate your database with every deployment, does that make sense? My current thinking is run database migrations separately and not as a part of the deployment to now. But I am also not sure, if this is better...

**Comment by ryanking1809** [comment]
@iherger I am running `prisma2 generate` first. Is there any reason you wouldn't want to check and run migrations on every deploy? I've always imagined it to be good practice.

**Comment by divyenduz** [comment]
Hi Everyone, is there anything actionable on this issue? I see that we have an example for now platform and thanks to @ryanking1809 (🙌)  we also have an example for zeit's now and nexus. 

If there is no open item, I will close this issue, we can branch off best practices discussion in a separate issue OR feel free to DM me about that in our slack. 

Closing this already, please ping me if you would like this to be reopened 🙏

**Comment by nhuesmann** [comment]
@divyenduz I just wanted to ping you because the example I could find for deploying prisma2 with Zeit Now ([this example](https://github.com/prisma/prisma-examples/tree/prisma2/deployment-platforms/zeit-now)) does not use Yoga, which is what I and I'm sure many others are using to build our Prisma servers. Do you have any examples of Prisma2 with Yoga deployed to Zeit Now 2?

Also a cherry on top would be how to do local development using `now dev`.

**Comment by iherger** [comment]
@nhuesmann , I made an example a while ago which works (I just updated it to the last versions of prisma and nexus): https://github.com/iherger/prisma2-now

**Comment by nhuesmann** [comment]
@iherger Thanks for sharing—have you been able to get local development working using `now dev`? I tried with your repo and it did not work. I have a `yarn workspaces` project in which my Prisma2 Yoga server is one of 3 backend microservices. I wanted to run the Prisma2 Yoga server with `now dev` since the rest of the microservices run with that command, however it's looking like that's not possible. I might just manually start the Yoga server with the start command then use `now dev` for everything else.

**Comment by iherger** [comment]
@nhuesmann , `now dev` works for me.

**Comment by nhuesmann** [comment]
@iherger Hmm... That's strange, I simply cloned your repo, installed deps, and tried `now dev`. Are you using a `.env` file in the project root that just has the `POSTGRESQL_URL` variable in it? That's the only additional thing I set up after cloning your repo. Also, what version of `now` do you have installed globally?

I will keep messing around with it, thanks for your reply.

**Comment by iherger** [comment]
@nhuesmann , I have an `.env` and a `.env.build` file with the `POSTGRESQL_URL` variable in it.

now version: 16.2.0.

I get all kinds of errors during the build, but the dev server starts alright, and I can query it. Both for this small project and for a larger project.

It could potentially also be an OS problem, I am using MacOS (10.14.6), but other than that, I don't know what could be wrong...

**Comment by nhuesmann** [comment]
@iherger I just tried the process again and got it to work :) I get tons of errors as well but playground loaded just fine and I was able to make GraphQL requests. I might have been having issues with my local postgres db, I wiped it entirely before trying this again. Thanks so much for providing your example and taking the time to help me, I really appreciate it!

**Comment by nhuesmann** [comment]
@iherger One last question that I'm not sure you know the answer to. I don't want this server to handle every route—I want it to be located at `http://localhost:3000/prisma`. When I try to change the src from `/(.*)` (the wildcard handler) to anything else, it doesn't work. If you don't have any idea why, don't sweat it :)
