### ISSUE TITLE
`prisma2 dev` should know and _only_ run migrations when there's an actual migration file that's not yet applied.

### ISSUE THREAD

**Issue by Dajust** [prisma/prisma2#37]
Hello,
Currently, after the initial successful migration, any attempt to restart dev mode via `prisma2 dev` will throw because the process tried to reapply already applied migration. Example error from [this comment](https://github.com/prisma/lift/issues/38#issuecomment-506652720):

```
thread 'main' panicked at 'The model Place already exists in this data model. It is not possible to create it once more.'
````

Thus, to be able to restart or use the dev mode again, the developer will need to first undo the initial migration via `prisma2 lift down`, or just delete the `_Migration` table from the DB. Personally, I do not  attempt to use the dev mode any more if the first instance was stopped for any reason.

 `prisma2 dev` should _*not always*_ run migrations and generate Photon/Nexus. It should be smart to know and only run migrations when there's an actual migration file that's not yet applied. If no not-yet-applied-migration, just skip the migration process and start the dev mode.

**Comment by auderer** [comment]
This error is also frequently occurring for me without ever running `prisma2 dev`.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting! @Dajust or @auderer: Do you have a reproduction for this?

**Comment by priley86** [comment]
this seems to be happening whenever you've created a database and run "lift up" to scaffold the initial schema without first creating an "initial migration" (with the same model). If an initial migration is created first (using "prisma lift save") before running "lift up" the first time, this does not seem to happen. 

Agree with the author though, `prisma2 dev` should intelligently determine if migrations need to be run (and not run them every time regardless).

Also running into [#25](https://github.com/prisma/lift/issues/25) on subsequent saves. Avoiding `primsa2 dev` for the time being due to this...

**Comment by divyenduz** [comment]
I am unable to reproduce this one, @priley86, @Dajust, @auderer can you provide a minimal reproduction with exact steps we can follow to reproduce this?

**Comment by pantharshit00** [comment]
I am also unable to reproduce this now, even with MySQL.

@priley86 Can you please share the version of Prisma 2 that you are using?

**Comment by priley86** [comment]
i'm using latest.. i'll see if i can't reproduce the exact steps and get back w/ you... 
https://github.com/priley86/how-to-graphql/blob/master/backend/Dockerfile#L2

you should be able to:
1. clone the repo there, 
2. Run npm start to  start the containers and scaffold the mysql database
3. then try adding a prisma schema change in [project.prisma](https://github.com/priley86/how-to-graphql/blob/master/backend/prisma/project.prisma), 
4. run `prisma2 lift save`, then `prisma2 lift up` from the `backend` folder to generate migrations
 (you'd need to install prisma2 globally the same way on your local)
5. then from the root of the project, re-run `npm run start` to start all containers (including the prisma dev console on http://localhost:5555). You'll see some migration errros...

This would effectively generate migrations AFTER initially scaffolding the db. The problem is, w/o an initial migration run at first, the migrations will try to recreate all tables. The dev console will try to run all migrations w/o scanning the database's _Migrations table first (that seems to be problem)...

this is a "nice-to-have" (b/c the workaround is to simply create an initial migration first and not do step 1 above).

hope it helps!

**Comment by pantharshit00** [comment]
This is expected as we can't apply the migration unless you save it using `prisma2 lift save`.

What prisma2 lift save, what lift is will is to create a `_Migrations` table in your database and it will store the migration metadata rows.

When you will run `prisma2 lift up` it will apply these migrations.

**Comment by priley86** [comment]
ok - good to know. Then I think I'm good. Not sure if @Dajust & @auderer are seeing something else though.

**Comment by pantharshit00** [comment]
Got a reproduction for the original issue: https://github.com/prisma/lift/issues/88#issue-476002405

I can confirm this now.

**Comment by pantharshit00** [comment]
I no longer can reproduce this issue with `prisma2@2.0.0-alpha.159, binary version: bbbeff6f84b408e534ebd866bfd378748e6d6611`
