### ISSUE TITLE
How to update datamodel schema to database(postgres) ?

### ISSUE THREAD

**Issue by sessionboy** [prisma/prisma2#490]
I created the project with prisma2 and did a migration job.
But when I changed the datamodel, I want to update it to the database. In `prisma v1` I can do this with `prisma deploy`, but in prisma2 I don't know how to update it to the database.

I tried using `prisma2 generate`, `prisma2 lift up`, `prisma2 lift save`,`prisma2 introspect`, but the schema of the database has not been the latest. It keeps the schema after migration.

I found a lift.lock file under the prisma/migrations directory. I don't know if it is related to this.

Now in order to update the datamodel, I have to delete the database schema and then re-execute the `prisma2 lift save` ,`prisma2 lift up` for migration. But I think this is definitely not the right way.

My version of prismav2 is:  prisma2@2.0.0-alpha.155

**Comment by pantharshit00** [comment]
Hi,

There are two ways you can update your database schema whenever you are changing the datamodel.

1. While in development, we provide a dedicated dev flow by using the `prisma2 dev` command. This will watch for changes in your datamodel and update your database schema whenever there is a change in your datamodel.

2. After you have done your work, you want to save your work to a migrations file so that you can apply these systematically in the future on an another database and communicate the changes with your team. For that, you will need to use the `prisma2 lift save` command. That will ask for a migration name and will create migration in the `migrations` folder. That will NOT apply the migration to the database. In order to apply these migrations, you will need to use `prisma2 lift up` command. Saving the migrations also comes with the benefit that you easily revert them using `prisma2 lift down` command.


I will recommend you to watch this talk from Prisma Day which has demo of this flow: https://www.youtube.com/watch?v=xfaps6hgFvI&list=PLn2e1F9Rfr6k7Xy9MLV-1wJG0bh7vzz-p&index=8

**Comment by sessionboy** [comment]
@pantharshit00  Thank you for your help.
I tried `prisma2 dev`, but it did not detect changes in `schema.prisma` ，the gui interface always shows `No changes yet`.

My `schema.prisma` has more than 300 lines of code. Now I try to delete some code, reduce it to 60 lines, then I try to change the datamodel and I am surprised to find that it actually works!  The schema of the database has been updated.

I tried to restore my code to more than 300 lines, then update the datamodel, I found that it didn't work, the gui interface shows `No changes yet` again.

I suspect this may be related to soket, which cannot be detected when schema.prisma becomes large.

**Comment by pantharshit00** [comment]
Can you please share your datamodel?

**Comment by sessionboy** [comment]
I am sorry, my company does not allow me to do this. Maybe you can test it yourself, when the schema.prisma is large, whether prisma2 dev will work.

I have a suggestion that `prisma cli` can provide a command to manually update the schema. When `prisma2 dev` does not work, we can manually update the schema via cli.

**Comment by pantharshit00** [comment]
Please try these sets of commands once.

```
prisma2 lift save
prisma2 lift up
```

That should migrate the database without involving the development flow.

**Comment by sessionboy** [comment]
I have tried it, it only works when it is first executed, it requires you to enter the version number of the migration. However, it does not work when it is executed later, and it cannot detect the change of `schema.prisma`, and there is no any terminal prompt.

**Comment by divyenduz** [comment]
@sessionboy Please run `prisma2 lift save` and `prisma2 lift up` command with `export DEBUG = *` environment variable set. Maybe there is an error that the CLI has but hides it in the interface.

**Comment by divyenduz** [comment]
I am closing this one due to inactivity, if you still think that this is an issue, please comment here and tag me. Thank you 🙏
