### ISSUE TITLE
Why does prisma2 cli prints things twice?

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/prisma2#569]
Probably a bug, but I don't know why I should read things twice 😂

<img width="1170" alt="twice" src="https://user-images.githubusercontent.com/16436270/65220751-15cc9c00-dad9-11e9-862f-12b9dfcbfbb1.png">

Took a long time to create this art ☝️🤣

**Comment by pantharshit00** [comment]
Hi,

I am unable to reproduce this.
![image](https://user-images.githubusercontent.com/22195362/65228554-4ff16a00-dae8-11e9-9edb-f674bc38b91c.png)

Can you please tell me the version of prisma2 that you are using(`prisma2 -v`)? I am using `prisma2@2.0.0-preview-12, binary version: 2292f8d0c3bd11fe9cca7c6df4a10061bf58fd18`

Also, please list out the exact steps that you took in order to trigger the above issue.

**Comment by deadcoder0904** [comment]
I have `prisma2@2.0.0-preview-11, binary version: 408c0c08746064a56c8ba7cb167bad49f1d2c2f7` which I just updated from `npm`. Idk when u released `preview-12` because [latest on npm](https://www.npmjs.com/package/prisma2) is also `preview-11` 😂

I selected `GraphQL` & `SQLite` :)

**Comment by deadcoder0904** [comment]
Weird, it doesn't show in `iTerm2` but I do get another error ⸺

```js
Preparing your starter kit: GraphQL API

✔  Downloading the starter kit from GitHub ...
✔  Extracting content to tttt ...
✔  Installing dependencies with: `npm install` ...
✔  Preparing your database ...
⠧  Seeding your database with: `npm run seed` ...
 ERROR  Error during command execution

~/tttt/prisma/seed.js:2
const photon = new Photon.default()
                          ^

TypeError: Cannot read property 'default' of undefined
    at Object.<anonymous> (~/tttt/prisma/seed.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-graphql@1.0.0 seed: `node prisma/seed.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-graphql@1.0.0 seed script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output abo
ve.

npm ERR! A complete log of this run can be found in:
npm ERR!
```

**Comment by pantharshit00** [comment]
It is updated in npm now 🙂. The `default()` issue was caused by a breaking change in preview-12. It should be gone now as we have updated the examples. 

I tried it in vscode but still can't reproduce it:

![image](https://user-images.githubusercontent.com/22195362/65241073-5095fa80-db00-11e9-8d41-44037d5ac07a.png)


Can you please try again now since `default()` issue is fixed.

**Comment by divyenduz** [comment]
@deadcoder0904 Do you have a specific theme for your VSCode terminal plugin?

**Comment by deadcoder0904** [comment]
The issue has been fixed now. Works well in VSCode terminal as well :)

> Do you have a specific theme for your VSCode terminal plugin?

I use [Oh My Zsh](https://ohmyz.sh/) in my Terminal & I have [agnostic](https://github.com/sseemayer/agnostic-zsh-theme) theme in `~/.zshrc`.

Just hate `npm install`. I'd appreciate #474. Any ETA?
