### ISSUE TITLE
How likely is Prisma going to survive?

### ISSUE THREAD

**Issue by brillout** [prisma/prisma2#636]
Prisma being a Startup, the question arises whether it will survive.

This directly affects the choice of whether I should use your tools.

What can make me believe that Prisma will survive in the years / decades to come?

That said, even if your answer is not convincing, I'll probably still try out and use Photon/Lift. But I do want to take an educated risk.

**Comment by zzyyzz1992** [comment]
Made in German

**Comment by robojones** [comment]
It's very nice. :+1:

**Comment by KrishnaPG** [comment]
Wondering the same. Without a strong use-case that is not covered by other middleware frameworks, it would be a risk to consider new frameworks.

JS is dynamic language, capable of generating the code on the fly, in memory. Next generation frameworks take advantage of this (e.g. Vue, React), and utilizing such capability, such as illustrated here https://github.com/prisma/prisma2/issues/708 , is one of the ways to ensure USP. Without such USP it is very difficult to make a point.

**Comment by idan** [comment]
Hi there! I'm Prisma's new head of product, and I'd like to share my perspective on the matter, as well as why I've decided to bet the next few years of my career on Prisma 😊

Whether or not we survive rests on two things: whether we're building the right thing, and whether we're executing well towards that goal. Finally, even if we do both of those things,we also need to earn your trust!

## Market

Our mission is to simplify data in the same way that compute has gotten easier to use over the last decade. Think about where compute was a decade ago — no Heroku, no Docker, no Kubernetes, no Lambda. No guidelines for architecture of scalable apps, like [12factor.net](https://12factor.net). The markets and businesses that have grown around simplifying compute are measured in the billions of dollars.

Data is no less of an opportunity. I believe it's a *much larger* opportunity. More than anything else, I think that's what makes Prisma durable. Prisma is unusually well-positioned to do something great in this valuable space and thrive as a business. The other half of that story is execution.

## Execution

We're a [well-funded](https://www.prisma.io/blog/prisma-raises-4-5m-to-build-the-graphql-data-layer-for-all-databases-663484df0f60/) company, and we will have more good news on that front soon! We have a stellar team, and [hiring](https://www.prisma.io/jobs) for a number of roles. All of our focus is on delivering on the upcoming [Prisma Framework](https://isprisma2ready.com), which is seeing preview releases every other week. We have a healthy business today and a long runway for execution.

This isn't our first rodeo. Graphcool and Prisma 1 were both attempts to figure out product-market fit. We have a headstart when it comes to understanding what matters, and spending our energies in the right place. We're not quite there yet, but we are getting very positive validation from our customers and partners as we make progress towards [releasing the Prisma Framework for production usage](http://isprisma2ready.com). Nothing is a guaranteed success in startups, but this is as close to ideal conditions as anyone can reasonably expect.

## Trust

Even if you believe in my take on the value of our business domain and our ability to execute, I think your core question is one of *trust*. Can you trust that we understand the landscape correctly and are building something people want? Can you trust that we're executing correctly and iterating towards something useful? When you ask whether we will still exist in a few years' time, those are the underlying questions I hear.

Trust isn't earned through words, but actions. On the execution front, we're already [releasing on a regular, frequent basis](https://github.com/prisma/prisma2/releases) to make sure that our progress is visible. We're working on having a more concrete public roadmap so you can plan ahead, with a more granularity than "everything is ready by `$DATE`". One of the concrete pieces of feedback that we hear from our community is that the release timeline for Prisma 2 has not been sufficiently clear. You can expect news about that in the coming weeks as we refine our plan and break it down into smaller, iterative chunks.

Finally, we're building a framework for your data. Unlike most webapps and libraries, we need you to trust that we will maintain the integrity of your data. That's a higher bar to meet than most. We're necessarily more cautious as a result, so that when we say that something is fit for production usage, we can sleep at night — and so can you.

Startups are risky, but clarity and execution is how we want to earn your trust. If there's something I can clarify, just ask! ✌️
