### ISSUE TITLE
OR operator not working

### ISSUE THREAD

**Issue by cypcz** [prisma/prisma2#659]
I am using the `OR` operator with the `where` clause. Like this:
```
        const user = await photon.users.findMany({
            where: {
                OR: {
                    username,
                    email
                }
            }
        })
```

My goal is to find users with either matched email or username. It finds users when the username matches but it won't find users when email matches.

Schema:
```
model User {
  id       String   @default(cuid()) @id
  email    String?  @unique
  username String   @unique
}
```

Am I using it wrong or is it a bug?

**Comment by pantharshit00** [comment]
Looks like a wrong usage of `OR` to me. I think the indented behaviour you are looking for can be achieved by the following code: 
```
const user = await photon.users.findMany({
    where: {
      OR: [
        {
          username: 'test',
        },
        {
          email: 'test',
        },
      ],
    },
  })
```


Any object without explicitly specifying the `OR` key on top will be connected by using `AND` implicitly. So your original code was checking for `username === 'something' && email == 'something'`. Since there was only one item in the `OR` array in the original code, there is no OR part in the final condition that was evaluated.

The code I have provided will perform the `username === 'something' || email == 'something'` check which I think is the required result in your code. 

I am going to close this issue. If you feel this hasn't been resolved yet, feel free to comment here or open a new issue.
