### ISSUE TITLE
Unable to get a writable SQLite DB working with Now 2

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma2#681]
I've been trying to get Studio running on Now 2 with Prisma2 + SQLite for preview deployments for all pull requests to the studio code repo. Everything is set up and working on https://prisma-studio.now.sh, except that the SQLite db file is readonly. This is evident by the following photon error when I try to write to the file (such as `photon.cities.create({ ... })`):

```
Error in Photon: 
Error: Reason: Error in connector: Error querying the database: attempt to write a readonly database

    at NodeEngine.handleErrors (/var/task/node_modules/@generated/climate/photon/runtime/index.js:4049:15)
    at currentRequestPromise.then (/var/task/node_modules/@generated/climate/photon/runtime/index.js:4009:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

@schickling suggested that I move the db file to `/tmp`, but that did not help either. I still see the same error.

I'm aware that expecting the DB to actually persist over a long period is not reasonable, but for the use case I'm after, that is irrelevant. What we want is a short-lived Studio deployment that can handle creates. It is absolutely okay if data is lost.

This is quite surely not a prisma2 issue, leaving this here for documentation + possible resolution with Now devs.

Relevant part of the schema:
```
datasource db {
  provider = "sqlite"
  url      = "file:/tmp/climate.db"
}

generator photon {
  provider = "photonjs"
  output   = "../../node_modules/@generated/climate/photon"
}
```

**Comment by pantharshit00** [comment]
Tmp directory won't work because build and prod containers are different so tmp data in build time is not copied to prod.

I investigated this and I was able to reproduce this, The file permission that is set by default are limiting and photon cannot write to the database. I even tried to change them using chmod and it was successfully done but zeit copies files from build to prod as far as I know and my guess is that the permission change was lost. I think it is serviceable by Zeit's end but they mentioned that SQLite is recommended in lambda environment:- 

![image](https://user-images.githubusercontent.com/22195362/66392849-a6b6d900-e9ee-11e9-85bd-b8b9b356cf13.png)


![image](https://user-images.githubusercontent.com/22195362/66392873-b2a29b00-e9ee-11e9-9465-399d8994846f.png)

**Comment by TooTallNate** [comment]
One thing you can do is:

 * During build-time, persist the initial sqlite database file into the serverless function output, which will cause it to be at `/var/task/climate.db` at runtime (read-only)
 * Then, during bootup of the serverless function, copy that initial `climate.db` file to `/tmp/climate.db` and reference that path in your configuration. It will be writable once residing in `/tmp`.

Hope that helps!

**Comment by divyenduz** [comment]
@madebysid Does this fix work for you?

**Comment by madebysid** [comment]
Closing this, decided to leave the deployment explicitly read-only with a warning, since it would reset any time I deploy a new version anyway. Appreciate the workaround though :)
