### ISSUE TITLE
Example projects creating dev migrations on install is unexpected

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#734]
Currently it seems that already during the installation of an example project via `init` `prisma2 dev` (or similar) is run to create some dev/watch migrations. That was unexpected to me and I am not sure if this should be this way.

**Comment by pantharshit00** [comment]
I also agree with this. No operation should be performed on database without giving an explicit command or agreeing to a prompt.

**Comment by pantharshit00** [comment]
Classifying this as a bug. Feel free to change the label if you feel like this is a regression because we were not creating the database in the old init flow.

**Comment by janpio** [comment]
> because we were not creating the database in the old init flow.

Is this correct @nikolasburk?

**Comment by nikolasburk** [comment]
This behaviour is actually correct. The reason is that we're also seeding the database so that users can immediately work with some real-looking data. In fact, the commands that are executed at the end of the `init` flow are dynamic, they're pulled fro the "examples API" based on this JSON file: https://github.com/prisma/prisma-examples/blob/master/.github/api.json#L20

**Comment by pantharshit00** [comment]
I think we should give user a prompt here.

```bash
--------------------------------------------------------
Do you want to seed your database with some sample data?
> Yes
  No
---------------------------------------------------------
```

**Comment by janpio** [comment]
I do not necessarily agree here @pantharshit00, this might as well be wanted behavior if it is contained to new and empty databases. What could improve, is the messages during the project creation.
