### ISSUE TITLE
Support all specced binary targets

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#749]
https://github.com/prisma/specs/tree/master/binaries#pre-built-binary-targets

The CLI only accepts  `native`, `darwin`, `linux-glibc-libssl1.0.1`, `linux-glibc-libssl1.0.2`, `linux-glibc-libssl1.1.0`, `linux-musl-libssl1.1.0`, `windows`, so i.e. libssl1.1.1 isnt' supported right now

**Comment by janpio** [comment]
Does this still apply after your pending changes to that spec @steebchen? Best provide a link to your current PR branch that contains the same information.

**Comment by steebchen** [comment]
Yeah, https://github.com/prisma/specs/pull/145 invalidates this.

@divyenduz We don't need to support patch versions, because they're compatible between other. Only major and minor versions are incompatible. Currently, this may not be true because we're building different libssl versions on different base operating system, which makes them incompatible with some OS by accident. This is fixed in my new spec but is not implemented yet.

**Comment by divyenduz** [comment]
@steebchen Yes, that is also my understanding from last time we spoke about it. Now we need to find some Dom, Tim time to implement it.

**Comment by divyenduz** [comment]
This is implemented with the new binary spec.
