### ISSUE TITLE
Document --unsafe-perm for all unix systems

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#931]
In my testing and reports by many users, npm requires `--unsafe-perm` if an install script if trying to modify data and it has root permissions. 

So we do need to document this properly. This is also important as it is the install step.

**Comment by LongLiveCHIEF** [comment]
This is a non-starter.  This particular setting is disallowed in most platforms, and if it's not, then when the uid/gid switches to root, the process will crash because _that_ setting is disallowed.

This is a container/cloud policy driven world these days. 

On top of that, having the download of this binary happen outside of the package manager installation is _also_ likely to fail, because these same types of environments generally don't have connections to the internet.

My thought is that you should really close this issue and instead open a new one "Find more secure and configuration/policy friendly way to install platform binary"

I'd hate for such a promising platform to fail to get traction because of something so central to it's design not being compatible with modern Infrastructure and security policies.

**Comment by LongLiveCHIEF** [comment]
I opened #938, which I believe should preempt and close this issue.

**Comment by pantharshit00** [comment]
Thanks, I agree with you.
