### ISSUE TITLE
Prisma2 and Babel

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma2#972]
I tried today to convert my build system with Babel. (preset-typescript).

When building no error, but at launch: `ReferenceError: regeneratorRuntime is not defined`

![image](https://user-images.githubusercontent.com/7302317/69426774-4fff2780-0d2e-11ea-9cb4-64ef0f9ea54c.png)

**Comment by pantharshit00** [comment]
Can you please share your `tsconfig.json` file? Also, please share your babelrc as well.

**Comment by yovanoc** [comment]
I'm in a yarn workspaces, so root tsconfig:

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "declaration": true,
    "declarationMap": true,
    "removeComments": true,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "incremental": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "skipLibCheck": true,
    "pretty": true,
    "noEmit": true,
    "baseUrl": ".",
    "paths": {
      "@com/*": ["packages/*/src"]
    }
  }
}
```

in my server project:

```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "rootDir": "src",
    "outDir": "dist",
    "declaration": true
  },
  "include": ["src"],
  "references": [
    {
      "path": "../common"
    },
    {
      "path": "../mail"
    }
  ]
}
```

and babelrc

```json
{
  "presets": ["@babel/preset-typescript", "@babel/preset-env", "minify"],
  "plugins": [
    "@babel/plugin-proposal-numeric-separator",
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread",
    "babel-plugin-const-enum"
  ]
}
```

**Comment by pantharshit00** [comment]
In your current babel setup, you are telling babel to compile the code for browser as you are not providing any options to `@babel/preset-env`. That means babel will transpile async await code to generators and expect you to include babel-runtime in order to save repeated code that is required by transpiled code.

So your transpiled code will contain the regeneratorRuntime:
![image](https://user-images.githubusercontent.com/22195362/69532872-bdb08b00-0f9c-11ea-8de9-e19d1322223a.png)


In order to fix this, you will need to tell babel to compile code for nodejs which already supports async/await syntax. To do so add node as the target in preset env(I have also fixed the names of plugins, in the config that you have shared, you didn't include `plugin` in front of them):
```json
{
  "presets": [
    "@babel/preset-typescript",
    ["@babel/preset-env", { "targets": { "node": true } }]
  ],
  "plugins": [
    "@babel/plugin-proposal-numeric-separator",
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread",
    "babel-plugin-const-enum"
  ]
}
```

Now babel will correctly transpile this code:
![image](https://user-images.githubusercontent.com/22195362/69533247-75459d00-0f9d-11ea-9be3-9a23e37b638d.png)

**Comment by yovanoc** [comment]
Ohhh yes my bad, thank you!

**Comment by pantharshit00** [comment]
Closing this now :)
