### ISSUE TITLE
Self referencing tables not supported

### ISSUE THREAD

**Issue by mendeljacks** [prisma/prisma2#991]
When using prisma2 with mysql/typescript I have found two scenarios which are not supported.

1. Any table where the foreign key references itself.
2. Any table which has two foreign keys to the same table

The use case for 1 could be a categories table where each category has a parent which is stored in the same table.

the use case for 2 could be a shipping table where the origin and destination warehouses both reference a warehouse in the same warehouses table.

Is there currently any plans to support these features? With a little support I'd be happy to give these features a go if desired

**Comment by pantharshit00** [comment]
Hi,

Yes, we support both of these use cases.

> Any table where the foreign key references itself.

You can express that like so in the schema:
```prisma
model Category {
  id         String    @id @default(cuid())
  name       String
  parent     Category? @relation(name: "CategoryParent")
  child      Category? @relation(name: "CategoryChild")
  parentBack Category? @relation(name: "CategoryParent")
  childBack  Category? @relation(name: "CategoryChild")
}
```
Note that backrelations are required so that we can disambiguate the relations. That will tell prisma that you are trying to reference the id field of the same model.

That will create the following database structure:
![image](https://user-images.githubusercontent.com/22195362/69652664-0731d080-1098-11ea-9807-dce14d596cd2.png)

We are also trying to improve this syntax: https://github.com/prisma/specs/pull/299


> Any table which has two foreign keys to the same table

Yes, we also support this but currently it is a bit buggy (see #976)

Example datamodel for this use case:
```prisma
model Warehouse {
  id       String     @id @default(cuid())
  name     String
  shipping Shipping[]
}

model Shipping {
  id          String    @id @default(cuid())
  address     String
  origin      Warehouse
  destination Warehouse
}
```

**Comment by divyenduz** [comment]
Closing this one, @mendeljacks If you think that @pantharshit00's answer does not address your question completely, please add a comment on this issue and tag me.
